//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UscProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BoxCategory()
        {
            this.OrderDetailTB = new HashSet<OrderDetailTB>();
        }
    
        public int BoxCategoryID { get; set; }
        public string BoxName { get; set; }
        public string BoxDescription { get; set; }
        public int Price { get; set; }
        public int DatePermission { get; set; }
        public int CountPermisson { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailTB> OrderDetailTB { get; set; }
    }
}
