//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UscProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactTB
    {
        public int ContactID { get; set; }
        public string ContactUserName { get; set; }
        public string ContactEmail { get; set; }
        public long ContactPhone { get; set; }
        public string ContactSubject { get; set; }
        public string ContactText { get; set; }
        public System.DateTime ContactDate { get; set; }
    }
}
