//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UscProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderDetailTB()
        {
            this.FormTB = new HashSet<FormTB>();
        }
    
        public int OrderDetailID { get; set; }
        public int BoxCategoryID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public bool Status { get; set; }
    
        public virtual BoxCategory BoxCategory { get; set; }
        public virtual EmployeeTB EmployeeTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormTB> FormTB { get; set; }
    }
}
