//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UscProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheTop5Employee
    {
        public int EmployeeID { get; set; }
        public int UserID { get; set; }
        public Nullable<long> PhoneNumber { get; set; }
        public string Site { get; set; }
        public string Adress { get; set; }
        public string CompanyName { get; set; }
    }
}
